#!/bin/bash

function PHD {
	 cd "/home/Kononov/Documents/DigiLab-Backup/BACKUP/PHD_theses"
	 emacsclient "/home/Kononov/Documents/DigiLab-Backup/BACKUP/PHD_theses/main.tex" &
}

function phdlatex {
    if [[ "$1" == "-h" ]] || [[ -z "$1" ]]; then
	printf "\nUsage: ${FUNCNAME[0]} [options] example.tex \n
Options:\n\t-h this help page\n\t-b run pdflatex than biber than pdflatex again\n\t-g run pdflatex than makeglossaries than pdflatex again\n\t\t
!!! your directory have to include 'latex_output' folder\n\t\t
So it basicaly runs pdflatex with  -output-directory='latex_output' and than extracts pdf file and puts it back into current and than one time biber latex_output/%name and agin pdflatex ...\n\n"
	return
    else
	rm *.aux		# clean up if sone one called pdflatex in the dir
	rm *.toc
	rm *.out
	rm *.log
	rm *.acn
	rm *.ist
	rm *.glo
	rm *.bcf
	rm *.sdn
	rm *.glsdefs
	rm *.run.xml
	if [[ "$1" == "-b" ]]
	then
	    IFS=. read -r  name ending <<< ${2}
	    pdflatex  -shell-escape -halt-on-error -output-directory="latex_output" "$2"
	    biber "latex_output/$name"
	    pdflatex  -shell-escape -halt-on-error -output-directory="latex_output" "$2"
	    mv "latex_output/$name.pdf" .
	elif [[ "$1" == "-g" ]]
	then
	    IFS=. read -r  name ending <<< ${2}
	    pdflatex  -shell-escape -halt-on-error -output-directory="latex_output" "$2"
	    makeglossaries -d "latex_output" "$name"
	    pdflatex -shell-escape -halt-on-error -output-directory="latex_output" "$2"
	    mv "latex_output/$name.pdf" .
	else
	    IFS=. read -r  name ending <<< ${1}
	    pdflatex  -shell-escape -halt-on-error -output-directory="latex_output" "$1"
	    mv "latex_output/$name.pdf" .
	fi
    fi
}


# function phdlatex {
#     pdflatex -output-directory=latex_output $1    
#     return
# }
